export function getDisc () {
  const data = [
    {
      'id': 0,
      'imgUrl': 'http://p1.music.126.net/PEt4a_iAF4gleuI218MEUg==/18585045046467791.webp?imageView&amp;thumbnail=246x0&amp;quality=75&amp;tostatic=0&amp;type=webp',
      'description': '再丑也要谈恋爱，谈到世界充满爱',
      'listenerNum': '104.5万'
    },
    {
      'id': 1,
      'imgUrl': 'http://p1.music.126.net/pMXWeBnsYez4QM9bkiweeg==/18811544441785113.webp?imageView&amp;thumbnail=246x0&amp;quality=75&amp;tostatic=0&amp;type=webp',
      'description': '『R&amp;B 精选』节奏音律中，总有适合的调调¶',
      'listenerNum': '35.3万'
    },
    {
      'id': 2,
      'imgUrl': 'http://p1.music.126.net/a3sVmFHLQs80XrXmF2GWfw==/18986366788933377.webp?imageView&amp;thumbnail=246x0&amp;quality=75&amp;tostatic=0&amp;type=webp',
      'description': '华语︱情话是一门失传的艺术',
      'listenerNum': '335.3万'
    },
    {
      'id': 3,
      'imgUrl': 'http://p1.music.126.net/KJl6zoi0v6O_EciV6apTQQ==/109951162915244001.webp?imageView&amp;thumbnail=246x0&amp;quality=75&amp;tostatic=0&amp;type=webp',
      'description': '慵懒与柔情 | 当吉他邂逅女声',
      'listenerNum': '600.1万'
    },
    {
      'id': 4,
      'imgUrl': 'http://p1.music.126.net/NcxIvOn6iuODW-5K-nE-ZQ==/18554258720776933.webp?imageView&amp;thumbnail=246x0&amp;quality=75&amp;tostatic=0&amp;type=webp',
      'description': '她，柔软是治愈的别名',
      'listenerNum': '73822'
    },
    {
      'id': 5,
      'imgUrl': 'http://p1.music.126.net/y2PYbL4FDWZ-MfmokfJE1w==/109951163084209063.webp?imageView&amp;thumbnail=246x0&amp;quality=75&amp;tostatic=0&amp;type=webp',
      'description': '台湾流行音乐简史二·思想起「1980—1984」',
      'listenerNum': '82.4万'
    }
  ]

  return new Promise((resolve) => {
    setTimeout(function () {
      resolve(data)
    }, 300)
  })
}

export function getLatestSongs () {
  /* eslint-disable */
  const data = {
    "code": 200,
    "category": 5,
    "result": [
      {
        "id": 528271287,
        "type": 4,
        "name": "犴达罕",
        "copywriter": null,
        "picUrl": null,
        "canDislike": false,
        "song": {
            "name": "犴达罕",
            "id": 528271287,
            "position": 1,
            "alias": [],
            "status": 0,
            "fee": 8,
            "copyrightId": 456010,
            "disc": "",
            "no": 0,
            "artists": [
                {
                    "name": "陈鸿宇",
                    "id": 1058228,
                    "picId": 0,
                    "img1v1Id": 0,
                    "briefDesc": "",
                    "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "albumSize": 0,
                    "alias": [],
                    "trans": "",
                    "musicSize": 0
                }
            ],
            "album": {
                "name": "犴达罕",
                "id": 37176088,
                "type": "EP/Single",
                "size": 1,
                "picId": 109951163101029180,
                "blurPicUrl": "http://p1.music.126.net/xd3UWxrOVrwwMPNQB8RfJw==/109951163101029187.jpg",
                "companyId": 0,
                "pic": 109951163101029180,
                "picUrl": "http://p1.music.126.net/xd3UWxrOVrwwMPNQB8RfJw==/109951163101029187.jpg",
                "publishTime": 1515254400007,
                "description": "",
                "tags": "",
                "company": "看见网络",
                "briefDesc": "",
                "artist": {
                    "name": "",
                    "id": 0,
                    "picId": 0,
                    "img1v1Id": 0,
                    "briefDesc": "",
                    "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "albumSize": 0,
                    "alias": [],
                    "trans": "",
                    "musicSize": 0
                },
                "songs": [],
                "alias": [],
                "status": 0,
                "copyrightId": 456010,
                "commentThreadId": "R_AL_3_37176088",
                "artists": [
                    {
                        "name": "陈鸿宇",
                        "id": 1058228,
                        "picId": 0,
                        "img1v1Id": 0,
                        "briefDesc": "",
                        "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                        "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                        "albumSize": 0,
                        "alias": [],
                        "trans": "",
                        "musicSize": 0
                    }
                ],
                "picId_str": "109951163101029187"
            },
            "starred": false,
            "popularity": 0,
            "score": 0,
            "starredNum": 0,
            "duration": 289109,
            "playedNum": 0,
            "dayPlays": 0,
            "hearTime": 0,
            "ringtone": null,
            "crbt": null,
            "audition": null,
            "copyFrom": "",
            "commentThreadId": "R_SO_4_528271287",
            "rtUrl": null,
            "ftype": 0,
            "rtUrls": [],
            "copyright": 0,
            "rtype": 0,
            "rurl": null,
            "hMusic": {
                "name": "",
                "id": 1405696176,
                "size": 11567064,
                "extension": "mp3",
                "sr": 44100,
                "dfsId": 0,
                "bitrate": 320000,
                "playTime": 289109,
                "volumeDelta": -1
            },
            "mMusic": {
                "name": "",
                "id": 1405696177,
                "size": 6940256,
                "extension": "mp3",
                "sr": 44100,
                "dfsId": 0,
                "bitrate": 192000,
                "playTime": 289109,
                "volumeDelta": -1
            },
            "lMusic": {
                "name": "",
                "id": 1405696178,
                "size": 4626852,
                "extension": "mp3",
                "sr": 44100,
                "dfsId": 0,
                "bitrate": 128000,
                "playTime": 289109,
                "volumeDelta": -1
            },
            "bMusic": {
                "name": "",
                "id": 1405696178,
                "size": 4626852,
                "extension": "mp3",
                "sr": 44100,
                "dfsId": 0,
                "bitrate": 128000,
                "playTime": 289109,
                "volumeDelta": -1
            },
            "mvid": 0,
            "mp3Url": null,
            "privilege": {
                "id": 528271287,
                "fee": 8,
                "payed": 0,
                "st": 0,
                "pl": 128000,
                "dl": 0,
                "sp": 7,
                "cp": 1,
                "subp": 1,
                "cs": false,
                "maxbr": 999000,
                "fl": 128000,
                "toast": false,
                "flag": 0,
                "preSell": false
            }
        },
        "alg": "featured"
      },
      {
          "id": 528273169,
          "type": 4,
          "name": "Filthy",
          "copywriter": null,
          "picUrl": null,
          "canDislike": false,
          "song": {
              "name": "Filthy",
              "id": 528273169,
              "position": 1,
              "alias": [],
              "status": 0,
              "fee": 8,
              "copyrightId": 7001,
              "disc": "1",
              "no": 1,
              "artists": [
                  {
                      "name": "Justin Timberlake",
                      "id": 35331,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  }
              ],
              "album": {
                  "name": "Filthy",
                  "id": 37179058,
                  "type": "EP/Single",
                  "size": 1,
                  "picId": 109951163100777220,
                  "blurPicUrl": "http://p1.music.126.net/6n6YlKZjV29I-FRvFjC-ig==/109951163100777209.jpg",
                  "companyId": 0,
                  "pic": 109951163100777220,
                  "picUrl": "http://p1.music.126.net/6n6YlKZjV29I-FRvFjC-ig==/109951163100777209.jpg",
                  "publishTime": 1515110400000,
                  "description": "",
                  "tags": "",
                  "company": "索尼音乐",
                  "briefDesc": "",
                  "artist": {
                      "name": "",
                      "id": 0,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  "songs": [],
                  "alias": [],
                  "status": 3,
                  "copyrightId": 7001,
                  "commentThreadId": "R_AL_3_37179058",
                  "artists": [
                      {
                          "name": "Justin Timberlake",
                          "id": 35331,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      }
                  ],
                  "picId_str": "109951163100777209"
              },
              "starred": false,
              "popularity": 100,
              "score": 100,
              "starredNum": 0,
              "duration": 294008,
              "playedNum": 0,
              "dayPlays": 0,
              "hearTime": 0,
              "ringtone": null,
              "crbt": null,
              "audition": null,
              "copyFrom": "",
              "commentThreadId": "R_SO_4_528273169",
              "rtUrl": null,
              "ftype": 0,
              "rtUrls": [],
              "copyright": 1,
              "rtype": 0,
              "rurl": null,
              "hMusic": {
                  "name": "",
                  "id": 1405471424,
                  "size": 11760370,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 320000,
                  "playTime": 294008,
                  "volumeDelta": -1
              },
              "mMusic": {
                  "name": "",
                  "id": 1405471425,
                  "size": 7056240,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 192000,
                  "playTime": 294008,
                  "volumeDelta": -1
              },
              "lMusic": {
                  "name": "",
                  "id": 1405471426,
                  "size": 4704174,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 294008,
                  "volumeDelta": -1
              },
              "bMusic": {
                  "name": "",
                  "id": 1405471426,
                  "size": 4704174,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 294008,
                  "volumeDelta": -1
              },
              "mvid": 5799032,
              "mp3Url": null,
              "privilege": {
                  "id": 528273169,
                  "fee": 8,
                  "payed": 0,
                  "st": 0,
                  "pl": 128000,
                  "dl": 0,
                  "sp": 7,
                  "cp": 1,
                  "subp": 1,
                  "cs": false,
                  "maxbr": 320000,
                  "fl": 128000,
                  "toast": false,
                  "flag": 0,
                  "preSell": false
              }
          },
          "alg": "featured"
      },
      {
          "id": 525112224,
          "type": 4,
          "name": "If You Leave Me Now",
          "copywriter": null,
          "picUrl": null,
          "canDislike": false,
          "song": {
              "name": "If You Leave Me Now",
              "id": 525112224,
              "position": 1,
              "alias": [],
              "status": 0,
              "fee": 8,
              "copyrightId": 7002,
              "disc": "1",
              "no": 1,
              "artists": [
                  {
                      "name": "Charlie Puth",
                      "id": 90331,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  {
                      "name": "Boyz II Men",
                      "id": 88168,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  }
              ],
              "album": {
                  "name": "If You Leave Me Now",
                  "id": 37003086,
                  "type": "EP/Single",
                  "size": 1,
                  "picId": 17958323416731584,
                  "blurPicUrl": "http://p1.music.126.net/qClFf-0KGy10QVRbUs_2YQ==/17958323416731585.jpg",
                  "companyId": 0,
                  "pic": 17958323416731584,
                  "picUrl": "http://p1.music.126.net/qClFf-0KGy10QVRbUs_2YQ==/17958323416731585.jpg",
                  "publishTime": 1514995200007,
                  "description": "",
                  "tags": "",
                  "company": "华纳唱片",
                  "briefDesc": "",
                  "artist": {
                      "name": "",
                      "id": 0,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  "songs": [],
                  "alias": [],
                  "status": 3,
                  "copyrightId": 7002,
                  "commentThreadId": "R_AL_3_37003086",
                  "artists": [
                      {
                          "name": "Charlie Puth",
                          "id": 90331,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      },
                      {
                          "name": "Boyz II Men",
                          "id": 88168,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      }
                  ],
                  "picId_str": "17958323416731585"
              },
              "starred": false,
              "popularity": 100,
              "score": 100,
              "starredNum": 0,
              "duration": 242207,
              "playedNum": 0,
              "dayPlays": 0,
              "hearTime": 0,
              "ringtone": null,
              "crbt": null,
              "audition": null,
              "copyFrom": "",
              "commentThreadId": "R_SO_4_525112224",
              "rtUrl": null,
              "ftype": 0,
              "rtUrls": [],
              "copyright": 1,
              "rtype": 0,
              "rurl": null,
              "hMusic": {
                  "name": "",
                  "id": 1404434770,
                  "size": 9689382,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 320000,
                  "playTime": 242207,
                  "volumeDelta": -2
              },
              "mMusic": {
                  "name": "",
                  "id": 1404434771,
                  "size": 5813647,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 192000,
                  "playTime": 242207,
                  "volumeDelta": -2
              },
              "lMusic": {
                  "name": "",
                  "id": 1404434772,
                  "size": 3875779,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 242207,
                  "volumeDelta": -1
              },
              "bMusic": {
                  "name": "",
                  "id": 1404434772,
                  "size": 3875779,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 242207,
                  "volumeDelta": -1
              },
              "mvid": 0,
              "mp3Url": null,
              "privilege": {
                  "id": 525112224,
                  "fee": 8,
                  "payed": 0,
                  "st": 0,
                  "pl": 128000,
                  "dl": 0,
                  "sp": 7,
                  "cp": 1,
                  "subp": 1,
                  "cs": false,
                  "maxbr": 320000,
                  "fl": 128000,
                  "toast": false,
                  "flag": 0,
                  "preSell": false
              }
          },
          "alg": "featured"
      },
      {
          "id": 526904220,
          "type": 4,
          "name": "20",
          "copywriter": null,
          "picUrl": null,
          "canDislike": true,
          "song": {
              "name": "20",
              "id": 526904220,
              "position": 1,
              "alias": [],
              "status": 0,
              "fee": 8,
              "copyrightId": 7002,
              "disc": "1",
              "no": 1,
              "artists": [
                  {
                      "name": "Ty.",
                      "id": 1086078,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  {
                      "name": "王心凌",
                      "id": 9606,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  }
              ],
              "album": {
                  "name": "20",
                  "id": 37099125,
                  "type": "EP/Single",
                  "size": 1,
                  "picId": 109951163097818640,
                  "blurPicUrl": "http://p1.music.126.net/zbGzIHKMot_wHVAt1HzwjQ==/109951163097818641.jpg",
                  "companyId": 0,
                  "pic": 109951163097818640,
                  "picUrl": "http://p1.music.126.net/zbGzIHKMot_wHVAt1HzwjQ==/109951163097818641.jpg",
                  "publishTime": 1514736000000,
                  "description": "",
                  "tags": "",
                  "company": "华纳唱片",
                  "briefDesc": "",
                  "artist": {
                      "name": "",
                      "id": 0,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  "songs": [],
                  "alias": [],
                  "status": 3,
                  "copyrightId": 7002,
                  "commentThreadId": "R_AL_3_37099125",
                  "artists": [
                      {
                          "name": "Ty.",
                          "id": 1086078,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      },
                      {
                          "name": "王心凌",
                          "id": 9606,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      }
                  ],
                  "picId_str": "109951163097818641"
              },
              "starred": false,
              "popularity": 50,
              "score": 50,
              "starredNum": 0,
              "duration": 196153,
              "playedNum": 0,
              "dayPlays": 0,
              "hearTime": 0,
              "ringtone": null,
              "crbt": null,
              "audition": null,
              "copyFrom": "",
              "commentThreadId": "R_SO_4_526904220",
              "rtUrl": null,
              "ftype": 0,
              "rtUrls": [],
              "copyright": 0,
              "rtype": 0,
              "rurl": null,
              "hMusic": {
                  "name": "",
                  "id": 1405012186,
                  "size": 7849317,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 320000,
                  "playTime": 196153,
                  "volumeDelta": 0
              },
              "mMusic": {
                  "name": "",
                  "id": 1405012187,
                  "size": 4709608,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 192000,
                  "playTime": 196153,
                  "volumeDelta": 0
              },
              "lMusic": {
                  "name": "",
                  "id": 1405012188,
                  "size": 3139753,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 196153,
                  "volumeDelta": 0
              },
              "bMusic": {
                  "name": "",
                  "id": 1405012188,
                  "size": 3139753,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 196153,
                  "volumeDelta": 0
              },
              "mvid": 5779391,
              "mp3Url": null,
              "exclusive": false,
              "privilege": {
                  "id": 526904220,
                  "fee": 8,
                  "payed": 0,
                  "st": 0,
                  "pl": 128000,
                  "dl": 0,
                  "sp": 7,
                  "cp": 1,
                  "subp": 1,
                  "cs": false,
                  "maxbr": 999000,
                  "fl": 128000,
                  "toast": false,
                  "flag": 0,
                  "preSell": false
              }
          },
          "alg": "hot_server"
      },
      {
          "id": 528271302,
          "type": 4,
          "name": "不完美 (Live版)",
          "copywriter": null,
          "picUrl": null,
          "canDislike": true,
          "song": {
              "name": "不完美 (Live版)",
              "id": 528271302,
              "position": 3,
              "alias": [],
              "status": 0,
              "fee": 8,
              "copyrightId": 0,
              "disc": "",
              "no": 3,
              "artists": [
                  {
                      "name": "岑宁儿",
                      "id": 7409,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  }
              ],
              "album": {
                  "name": "Stage舞台 第1季",
                  "id": 37026191,
                  "type": "专辑",
                  "size": 3,
                  "picId": 109951163090171970,
                  "blurPicUrl": "http://p1.music.126.net/qdA0i_BwZDIsLQNjypfVPw==/109951163090171973.jpg",
                  "companyId": 0,
                  "pic": 109951163090171970,
                  "picUrl": "http://p1.music.126.net/qdA0i_BwZDIsLQNjypfVPw==/109951163090171973.jpg",
                  "publishTime": 1515168000007,
                  "description": "",
                  "tags": "",
                  "company": "",
                  "briefDesc": "",
                  "artist": {
                      "name": "",
                      "id": 0,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  "songs": [],
                  "alias": [],
                  "status": 0,
                  "copyrightId": 0,
                  "commentThreadId": "R_AL_3_37026191",
                  "artists": [
                      {
                          "name": "群星",
                          "id": 122455,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      }
                  ],
                  "picId_str": "109951163090171973"
              },
              "starred": false,
              "popularity": 0,
              "score": 0,
              "starredNum": 0,
              "duration": 281640,
              "playedNum": 0,
              "dayPlays": 0,
              "hearTime": 0,
              "ringtone": null,
              "crbt": null,
              "audition": null,
              "copyFrom": "",
              "commentThreadId": "R_SO_4_528271302",
              "rtUrl": null,
              "ftype": 0,
              "rtUrls": [],
              "copyright": 0,
              "rtype": 0,
              "rurl": null,
              "hMusic": {
                  "name": "",
                  "id": 1405864281,
                  "size": 11268223,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 320000,
                  "playTime": 281640,
                  "volumeDelta": 2
              },
              "mMusic": {
                  "name": "",
                  "id": 1405864282,
                  "size": 6760951,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 192000,
                  "playTime": 281640,
                  "volumeDelta": 3
              },
              "lMusic": {
                  "name": "",
                  "id": 1405864283,
                  "size": 4507315,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 281640,
                  "volumeDelta": 3
              },
              "bMusic": {
                  "name": "",
                  "id": 1405864283,
                  "size": 4507315,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 281640,
                  "volumeDelta": 3
              },
              "mvid": 5779543,
              "mp3Url": null,
              "exclusive": true,
              "privilege": {
                  "id": 528271302,
                  "fee": 8,
                  "payed": 0,
                  "st": 0,
                  "pl": 128000,
                  "dl": 0,
                  "sp": 7,
                  "cp": 1,
                  "subp": 1,
                  "cs": false,
                  "maxbr": 999000,
                  "fl": 128000,
                  "toast": false,
                  "flag": 0,
                  "preSell": false
              }
          },
          "alg": "hot_server"
      },
      {
          "id": 528335230,
          "type": 4,
          "name": "For You",
          "copywriter": null,
          "picUrl": null,
          "canDislike": true,
          "song": {
              "name": "For You",
              "id": 528335230,
              "position": 1,
              "alias": [
                  "电影《五十度飞》主题曲"
              ],
              "status": 0,
              "fee": 8,
              "copyrightId": 7003,
              "disc": "1",
              "no": 1,
              "artists": [
                  {
                      "name": "Liam Payne",
                      "id": 12073104,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  {
                      "name": "Rita Ora",
                      "id": 74575,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  }
              ],
              "album": {
                  "name": "For You",
                  "id": 37121118,
                  "type": "EP/Single",
                  "size": 1,
                  "picId": 109951163100629040,
                  "blurPicUrl": "http://p1.music.126.net/dGuuFjv5EJ8djzk3CNC43A==/109951163100629037.jpg",
                  "companyId": 0,
                  "pic": 109951163100629040,
                  "picUrl": "http://p1.music.126.net/dGuuFjv5EJ8djzk3CNC43A==/109951163100629037.jpg",
                  "publishTime": 1515081600007,
                  "description": "",
                  "tags": "",
                  "company": "环球唱片",
                  "briefDesc": "",
                  "artist": {
                      "name": "",
                      "id": 0,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  "songs": [],
                  "alias": [
                      "电影《五十度飞》主题曲"
                  ],
                  "status": 3,
                  "copyrightId": 7003,
                  "commentThreadId": "R_AL_3_37121118",
                  "artists": [
                      {
                          "name": "Liam Payne",
                          "id": 12073104,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      },
                      {
                          "name": "Rita Ora",
                          "id": 74575,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      }
                  ],
                  "picId_str": "109951163100629037"
              },
              "starred": false,
              "popularity": 100,
              "score": 100,
              "starredNum": 0,
              "duration": 244323,
              "playedNum": 0,
              "dayPlays": 0,
              "hearTime": 0,
              "ringtone": null,
              "crbt": null,
              "audition": null,
              "copyFrom": "",
              "commentThreadId": "R_SO_4_528335230",
              "rtUrl": null,
              "ftype": 0,
              "rtUrls": [],
              "copyright": 1,
              "rtype": 0,
              "rurl": null,
              "hMusic": {
                  "name": "",
                  "id": 1405404187,
                  "size": 9774019,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 320000,
                  "playTime": 244323,
                  "volumeDelta": -2
              },
              "mMusic": {
                  "name": "",
                  "id": 1405404188,
                  "size": 5864429,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 192000,
                  "playTime": 244323,
                  "volumeDelta": -2
              },
              "lMusic": {
                  "name": "",
                  "id": 1405404189,
                  "size": 3909634,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 244323,
                  "volumeDelta": -2
              },
              "bMusic": {
                  "name": "",
                  "id": 1405404189,
                  "size": 3909634,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 244323,
                  "volumeDelta": -2
              },
              "mvid": 0,
              "mp3Url": null,
              "exclusive": false,
              "privilege": {
                  "id": 528335230,
                  "fee": 8,
                  "payed": 0,
                  "st": 0,
                  "pl": 128000,
                  "dl": 128000,
                  "sp": 7,
                  "cp": 1,
                  "subp": 1,
                  "cs": false,
                  "maxbr": 320000,
                  "fl": 128000,
                  "toast": false,
                  "flag": 4,
                  "preSell": false
              }
          },
          "alg": "hot_server"
      },
      {
          "id": 526929981,
          "type": 4,
          "name": "All The Stars",
          "copywriter": null,
          "picUrl": null,
          "canDislike": true,
          "song": {
              "name": "All The Stars",
              "id": 526929981,
              "position": 1,
              "alias": [
                  "电影《黑豹》插曲"
              ],
              "status": 0,
              "fee": 8,
              "copyrightId": 7003,
              "disc": "1",
              "no": 1,
              "artists": [
                  {
                      "name": "Kendrick Lamar",
                      "id": 37995,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  {
                      "name": "SZA",
                      "id": 905232,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  }
              ],
              "album": {
                  "name": "All The Stars",
                  "id": 37121095,
                  "type": "EP/Single",
                  "size": 1,
                  "picId": 109951163100540640,
                  "blurPicUrl": "http://p1.music.126.net/L28VPNn3TzNnYm_UsmjVxw==/109951163100540642.jpg",
                  "companyId": 0,
                  "pic": 109951163100540640,
                  "picUrl": "http://p1.music.126.net/L28VPNn3TzNnYm_UsmjVxw==/109951163100540642.jpg",
                  "publishTime": 1514995200007,
                  "description": "",
                  "tags": "",
                  "company": "环球唱片",
                  "briefDesc": "",
                  "artist": {
                      "name": "",
                      "id": 0,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  "songs": [],
                  "alias": [
                      "电影《黑豹》插曲"
                  ],
                  "status": 3,
                  "copyrightId": 7003,
                  "commentThreadId": "R_AL_3_37121095",
                  "artists": [
                      {
                          "name": "Kendrick Lamar",
                          "id": 37995,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      },
                      {
                          "name": "SZA",
                          "id": 905232,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      }
                  ],
                  "picId_str": "109951163100540642"
              },
              "starred": false,
              "popularity": 100,
              "score": 100,
              "starredNum": 0,
              "duration": 235572,
              "playedNum": 0,
              "dayPlays": 0,
              "hearTime": 0,
              "ringtone": null,
              "crbt": null,
              "audition": null,
              "copyFrom": "",
              "commentThreadId": "R_SO_4_526929981",
              "rtUrl": null,
              "ftype": 0,
              "rtUrls": [],
              "copyright": 1,
              "rtype": 0,
              "rurl": null,
              "hMusic": {
                  "name": "",
                  "id": 1405183955,
                  "size": 9423978,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 320000,
                  "playTime": 235572,
                  "volumeDelta": -2
              },
              "mMusic": {
                  "name": "",
                  "id": 1405183956,
                  "size": 5654404,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 192000,
                  "playTime": 235572,
                  "volumeDelta": -1
              },
              "lMusic": {
                  "name": "",
                  "id": 1405183957,
                  "size": 3769617,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 235572,
                  "volumeDelta": -1
              },
              "bMusic": {
                  "name": "",
                  "id": 1405183957,
                  "size": 3769617,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 235572,
                  "volumeDelta": -1
              },
              "mvid": 0,
              "mp3Url": null,
              "exclusive": false,
              "privilege": {
                  "id": 526929981,
                  "fee": 8,
                  "payed": 0,
                  "st": 0,
                  "pl": 128000,
                  "dl": 128000,
                  "sp": 7,
                  "cp": 1,
                  "subp": 1,
                  "cs": false,
                  "maxbr": 320000,
                  "fl": 128000,
                  "toast": false,
                  "flag": 4,
                  "preSell": false
              }
          },
          "alg": "hot_server"
      },
      {
          "id": 528271019,
          "type": 4,
          "name": "无常",
          "copywriter": null,
          "picUrl": null,
          "canDislike": true,
          "song": {
              "name": "无常",
              "id": 528271019,
              "position": 1,
              "alias": [],
              "status": 0,
              "fee": 8,
              "copyrightId": 636011,
              "disc": "",
              "no": 1,
              "artists": [
                  {
                      "name": "于湉",
                      "id": 905413,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  }
              ],
              "album": {
                  "name": "无常",
                  "id": 37176012,
                  "type": "EP/Single",
                  "size": 2,
                  "picId": 109951163099958980,
                  "blurPicUrl": "http://p1.music.126.net/RMW409XkNNi_hOb08wOJQA==/109951163099958971.jpg",
                  "companyId": 0,
                  "pic": 109951163099958980,
                  "picUrl": "http://p1.music.126.net/RMW409XkNNi_hOb08wOJQA==/109951163099958971.jpg",
                  "publishTime": 1515081600007,
                  "description": "",
                  "tags": "",
                  "company": "天娱传媒",
                  "briefDesc": "",
                  "artist": {
                      "name": "",
                      "id": 0,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  "songs": [],
                  "alias": [],
                  "status": 0,
                  "copyrightId": 636011,
                  "commentThreadId": "R_AL_3_37176012",
                  "artists": [
                      {
                          "name": "于湉",
                          "id": 905413,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      }
                  ],
                  "picId_str": "109951163099958971"
              },
              "starred": false,
              "popularity": 100,
              "score": 100,
              "starredNum": 0,
              "duration": 222366,
              "playedNum": 0,
              "dayPlays": 0,
              "hearTime": 0,
              "ringtone": null,
              "crbt": null,
              "audition": null,
              "copyFrom": "",
              "commentThreadId": "R_SO_4_528271019",
              "rtUrl": null,
              "ftype": 0,
              "rtUrls": [],
              "copyright": 0,
              "rtype": 0,
              "rurl": null,
              "hMusic": {
                  "name": "",
                  "id": 1404667726,
                  "size": 8897350,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 320000,
                  "playTime": 222366,
                  "volumeDelta": 0
              },
              "mMusic": {
                  "name": "",
                  "id": 1404667727,
                  "size": 5338427,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 192000,
                  "playTime": 222366,
                  "volumeDelta": 0
              },
              "lMusic": {
                  "name": "",
                  "id": 1404667728,
                  "size": 3558966,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 222366,
                  "volumeDelta": 0
              },
              "bMusic": {
                  "name": "",
                  "id": 1404667728,
                  "size": 3558966,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 222366,
                  "volumeDelta": 0
              },
              "mvid": 0,
              "mp3Url": null,
              "exclusive": true,
              "privilege": {
                  "id": 528271019,
                  "fee": 8,
                  "payed": 0,
                  "st": 0,
                  "pl": 128000,
                  "dl": 0,
                  "sp": 7,
                  "cp": 1,
                  "subp": 1,
                  "cs": false,
                  "maxbr": 999000,
                  "fl": 128000,
                  "toast": false,
                  "flag": 0,
                  "preSell": false
              }
          },
          "alg": "hot_server"
      },
      {
          "id": 526883263,
          "type": 4,
          "name": "So Far Away (CMC$ Remix)",
          "copywriter": null,
          "picUrl": null,
          "canDislike": true,
          "song": {
              "name": "So Far Away (CMC$ Remix)",
              "id": 526883263,
              "position": 1,
              "alias": [],
              "status": 0,
              "fee": 8,
              "copyrightId": 7001,
              "disc": "1",
              "no": 1,
              "artists": [
                  {
                      "name": "Martin Garrix",
                      "id": 780003,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  {
                      "name": "David Guetta",
                      "id": 31211,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  {
                      "name": "Jamie Scott",
                      "id": 141813,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  {
                      "name": "Romy Dya",
                      "id": 12900365,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  {
                      "name": "CMC$",
                      "id": 1086052,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  }
              ],
              "album": {
                  "name": "So Far Away (Remixes Vol. 2)",
                  "id": 37052480,
                  "type": "EP/Single",
                  "size": 5,
                  "picId": 109951163095249920,
                  "blurPicUrl": "http://p1.music.126.net/fNxE87W6wFnWd35cfcAW9g==/109951163095249917.jpg",
                  "companyId": 0,
                  "pic": 109951163095249920,
                  "picUrl": "http://p1.music.126.net/fNxE87W6wFnWd35cfcAW9g==/109951163095249917.jpg",
                  "publishTime": 1515081600007,
                  "description": "",
                  "tags": "",
                  "company": "索尼音乐",
                  "briefDesc": "",
                  "artist": {
                      "name": "",
                      "id": 0,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  "songs": [],
                  "alias": [],
                  "status": 3,
                  "copyrightId": 7001,
                  "commentThreadId": "R_AL_3_37052480",
                  "artists": [
                      {
                          "name": "Martin Garrix",
                          "id": 780003,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      }
                  ],
                  "picId_str": "109951163095249917"
              },
              "starred": false,
              "popularity": 100,
              "score": 100,
              "starredNum": 0,
              "duration": 166948,
              "playedNum": 0,
              "dayPlays": 0,
              "hearTime": 0,
              "ringtone": null,
              "crbt": null,
              "audition": null,
              "copyFrom": "",
              "commentThreadId": "R_SO_4_526883263",
              "rtUrl": null,
              "ftype": 0,
              "rtUrls": [],
              "copyright": 1,
              "rtype": 0,
              "rurl": null,
              "hMusic": {
                  "name": "",
                  "id": 1403929457,
                  "size": 6679031,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 320000,
                  "playTime": 166948,
                  "volumeDelta": -3
              },
              "mMusic": {
                  "name": "",
                  "id": 1403929458,
                  "size": 4007436,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 192000,
                  "playTime": 166948,
                  "volumeDelta": -3
              },
              "lMusic": {
                  "name": "",
                  "id": 1403929459,
                  "size": 2671639,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 166948,
                  "volumeDelta": -3
              },
              "bMusic": {
                  "name": "",
                  "id": 1403929459,
                  "size": 2671639,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 166948,
                  "volumeDelta": -3
              },
              "mvid": 0,
              "mp3Url": null,
              "exclusive": false,
              "privilege": {
                  "id": 526883263,
                  "fee": 8,
                  "payed": 0,
                  "st": 0,
                  "pl": 128000,
                  "dl": 0,
                  "sp": 7,
                  "cp": 1,
                  "subp": 1,
                  "cs": false,
                  "maxbr": 320000,
                  "fl": 128000,
                  "toast": false,
                  "flag": 0,
                  "preSell": false
              }
          },
          "alg": "hot_server"
      },
      {
          "id": 526904664,
          "type": 4,
          "name": "杀无赦",
          "copywriter": null,
          "picUrl": null,
          "canDislike": true,
          "song": {
              "name": "杀无赦",
              "id": 526904664,
              "position": 1,
              "alias": [
                  "电影《杀无赦》同名主题曲"
              ],
              "status": 0,
              "fee": 0,
              "copyrightId": 417014,
              "disc": "1",
              "no": 1,
              "artists": [
                  {
                      "name": "艾福杰尼",
                      "id": 12127564,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  {
                      "name": "BooM黄旭",
                      "id": 12065096,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  }
              ],
              "album": {
                  "name": "杀无赦",
                  "id": 37099184,
                  "type": "EP/Single",
                  "size": 2,
                  "picId": 109951163099042260,
                  "blurPicUrl": "http://p1.music.126.net/ZL-h8d20fakGYxzSfSt5Xg==/109951163099042254.jpg",
                  "companyId": 0,
                  "pic": 109951163099042260,
                  "picUrl": "http://p1.music.126.net/ZL-h8d20fakGYxzSfSt5Xg==/109951163099042254.jpg",
                  "publishTime": 1514908800000,
                  "description": "",
                  "tags": "",
                  "company": "自在天浩",
                  "briefDesc": "",
                  "artist": {
                      "name": "",
                      "id": 0,
                      "picId": 0,
                      "img1v1Id": 0,
                      "briefDesc": "",
                      "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                      "albumSize": 0,
                      "alias": [],
                      "trans": "",
                      "musicSize": 0
                  },
                  "songs": [],
                  "alias": [
                      "电影《杀无赦》同名主题曲"
                  ],
                  "status": 0,
                  "copyrightId": 417014,
                  "commentThreadId": "R_AL_3_37099184",
                  "artists": [
                      {
                          "name": "艾福杰尼",
                          "id": 12127564,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      },
                      {
                          "name": "BooM黄旭",
                          "id": 12065096,
                          "picId": 0,
                          "img1v1Id": 0,
                          "briefDesc": "",
                          "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                          "albumSize": 0,
                          "alias": [],
                          "trans": "",
                          "musicSize": 0
                      }
                  ],
                  "picId_str": "109951163099042254"
              },
              "starred": false,
              "popularity": 100,
              "score": 100,
              "starredNum": 0,
              "duration": 190791,
              "playedNum": 0,
              "dayPlays": 0,
              "hearTime": 0,
              "ringtone": null,
              "crbt": null,
              "audition": null,
              "copyFrom": "",
              "commentThreadId": "R_SO_4_526904664",
              "rtUrl": null,
              "ftype": 0,
              "rtUrls": [],
              "copyright": 2,
              "rtype": 0,
              "rurl": null,
              "hMusic": {
                  "name": "",
                  "id": 1404931957,
                  "size": 7634068,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 320000,
                  "playTime": 190791,
                  "volumeDelta": -2
              },
              "mMusic": {
                  "name": "",
                  "id": 1404931958,
                  "size": 4580458,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 192000,
                  "playTime": 190791,
                  "volumeDelta": -2
              },
              "lMusic": {
                  "name": "",
                  "id": 1404931959,
                  "size": 3053653,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 190791,
                  "volumeDelta": -2
              },
              "bMusic": {
                  "name": "",
                  "id": 1404931959,
                  "size": 3053653,
                  "extension": "mp3",
                  "sr": 44100,
                  "dfsId": 0,
                  "bitrate": 128000,
                  "playTime": 190791,
                  "volumeDelta": -2
              },
              "mvid": 5799017,
              "mp3Url": null,
              "exclusive": false,
              "privilege": {
                  "id": 526904664,
                  "fee": 0,
                  "payed": 0,
                  "st": 0,
                  "pl": 320000,
                  "dl": 320000,
                  "sp": 7,
                  "cp": 1,
                  "subp": 1,
                  "cs": false,
                  "maxbr": 999000,
                  "fl": 320000,
                  "toast": false,
                  "flag": 0,
                  "preSell": false
              }
          },
          "alg": "hot_server"
      }
    ]
  }

  return new Promise((resolve) => {
    setTimeout(function () {
      resolve(data)
    }, 300)
  })
}
